services:
  # Cloudflare Tunnel: Securely expose local services to the internet
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    dns:
      - 1.1.1.1
      - 1.0.0.1
    network_mode: "host"
    restart: unless-stopped
    depends_on:
      - svr_n8n

  svr_n8n:
    image: n8nio/n8n
    container_name: cont_n8n
    env_file:
      - .env
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_HOST=${N8N_HOST}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    ports:
      - "5678:5678"
    volumes:
      - ./vol_n8n:/home/node/.n8n
    restart: always