version: '3.7'
services:
  svr_n8n:
    image: n8nio/n8n
    container_name: cont_n8n
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_EDITOR_BASE_URL=https://n8n.hungngquang.xyz/
      - WEBHOOK_URL=https://n8n.hungngquang.xyz/
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_HOST=n8n.hungngquang.xyz
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    ports:
      - "5678:5678"
    volumes:
      - ./vol_n8n:/home/node/.n8n
    restart: always